"""
Builds sample_data.xlsx: a SYNTHETIC stand-in for the withheld case-study
workbook. It has the same sheet layout, column headers, and item names the
simulation expects, but every price, cost, unit count, rating, and sell-through
value is randomly generated. Results from it are illustrative only.

Run:
    python make_sample_data.py
"""

import numpy as np
import openpyxl

SEED = 2024
OUT = "sample_data.xlsx"

CURRENT_HEADER = [
    "Item", "Category", "Current Channel", "Current Facings", "Required Facings",
    "Retail Price", "Unit Cost", "Units Bought", "Units Sold Full Price",
    "Units Sold Clearance", "Store Units", "Online Units", "Star Rating",
    "# Reviews", "Total Sales $", "Gross Margin $", "Gross Margin Rate",
    "Full-Price Sell-Through", "GM $ per Facing",
]
NEW_HEADER = [
    "Item", "Category", "Required Facings", "Proposed Retail", "Unit Cost",
    "Mandatory Purchase Quanity", "Licensed?", "Vendor Says", "Merchant Notes",
    "Estimated Unit Margin $", "Estimated Unit Margin Rate",
    "Potential GM $ based on Purchase Quantity",
]

G, I, D = "Giants & Animatronics", "Inflatables", "Decor & Accessories"

# (item, category, channel, current facings, required facings)
CURRENT = [
    ("12 ft Giant Skeleton", G, "In-Store", 3, 3),
    ("9 ft Animated Pirate Ship", G, "In-Store", 2, 2),
    ("7 ft Animated Reaper", G, "In-Store", 1, 1),
    ("5.5 ft LED Skeleton Pony", G, "In-Store", 1, 1),
    ("10.5 ft Licensed Character Inflatable", I, "In-Store", 2, 2),
    ("9.5 ft Licensed Sandworm Inflatable", I, "In-Store", 1, 1),
    ("12 ft Reaper Inflatable", I, "In-Store", 1, 1),
    ("6 ft Scarecrow Inflatable", I, "In-Store", 1, 1),
    ("24 in Metal Tombstone", D, "In-Store", 1, 1),
    ("5 ft Skeleton Tombstone", D, "In-Store", 1, 1),
    ("LED Fog Machine", D, "In-Store", 1, 1),
    ("Pathway Light Set (6-piece)", D, "In-Store", 1, 1),
    ("16 ft Inflatable Haunted Archway", I, "Online-Only", 0, 3),
    ("Life-Size Animated Butler", G, "Online-Only", 0, 2),
    ("Animated Witch Cauldron", D, "Online-Only", 0, 1),
    ("Halloween Doormat Assortment", D, "Online-Only", 0, 1),
]

# (item, category, required facings, licensed)
NEW = [
    ("14 ft Giant Animated Dragon", G, 4, "No"),
    ("6 ft Licensed Movie Villain", G, 2, "Yes"),
    ("9 ft Licensed Franchise Inflatable", I, 2, "Yes"),
    ("7 ft Licensed Sitcom Character", G, 2, "Yes"),
    ("8 ft Inflatable Black Cat", I, 1, "No"),
    ("12 ft Inflatable Haunted Tree", I, 2, "No"),
    ("Fog Machine w/ Bluetooth Sound", D, 1, "No"),
    ("Animated Talking Portrait", D, 1, "No"),
    ("Solar Pathway Ghosts (4-pc)", D, 1, "No"),
    ("24 in Light-Up Pumpkin Stack", D, 1, "No"),
]

PRICE_RANGE = {G: (120, 450), I: (50, 260), D: (20, 90)}
UNITS_RANGE = {G: (4000, 30000), I: (5000, 25000), D: (5000, 30000)}


def main():
    rng = np.random.default_rng(SEED)
    wb = openpyxl.Workbook()

    readme = wb.active
    readme.title = "Read Me"
    readme["A1"] = "SYNTHETIC SAMPLE DATA"
    readme["A3"] = (
        "The real Halloween Decor case-study workbook is withheld. This file mirrors its "
        "layout, column headers, and item names so the code runs, but all numeric values "
        "are randomly generated and mean nothing. Generated by make_sample_data.py."
    )

    ws = wb.create_sheet("Student Data")
    ws["A1"] = "Student Data (SYNTHETIC SAMPLE)"
    ws["A2"] = "Randomly generated values with the same structure as the real workbook."
    ws["A4"] = "Current Assortment - Last Season Results"
    for j, h in enumerate(CURRENT_HEADER, 1):
        ws.cell(row=5, column=j, value=h)

    row = 6
    for name, cat, channel, cur_f, req_f in CURRENT:
        lo, hi = PRICE_RANGE[cat]
        retail = round(float(rng.uniform(lo, hi)), 2)
        cost = round(retail * float(rng.uniform(0.25, 0.60)), 2)
        ulo, uhi = UNITS_RANGE[cat]
        bought = int(round(rng.uniform(ulo, uhi), -2))
        st = round(float(rng.uniform(0.40, 0.95)), 2)
        full = int(round(bought * st))
        clear = bought - full
        if channel == "Online-Only":
            store_u, online_u = 0, bought
        else:
            store_u = int(round(bought * float(rng.uniform(0.30, 0.70))))
            online_u = bought - store_u
        stars = round(float(rng.uniform(3.9, 5.0)), 1)
        reviews = int(rng.integers(5, 2000))
        sales = full * retail + clear * retail * 0.5
        gm = sales - bought * cost
        vals = [
            name, cat, channel, cur_f, req_f, retail, cost, bought, full, clear,
            store_u, online_u, stars, reviews, round(sales, 2), round(gm, 2),
            gm / sales, st, (gm / cur_f) if cur_f else None,
        ]
        for j, v in enumerate(vals, 1):
            ws.cell(row=row, column=j, value=v)
        row += 1

    row = 25
    ws.cell(row=row, column=1, value="New Product Candidates - Supplier Offer Sheet")
    row += 1
    for j, h in enumerate(NEW_HEADER, 1):
        ws.cell(row=row, column=j, value=h)
    row += 1
    for name, cat, req_f, licensed in NEW:
        lo, hi = PRICE_RANGE[cat]
        retail = round(float(rng.uniform(lo, hi)), 2)
        cost = round(retail * float(rng.uniform(0.15, 0.75)), 2)
        qty = int(round(rng.uniform(6000, 30000), -3))
        unit_margin = round(retail - cost, 2)
        vals = [
            name, cat, req_f, retail, cost, qty, licensed,
            "Synthetic placeholder text.", "Synthetic placeholder text.",
            unit_margin, unit_margin / retail, round(unit_margin * qty, 2),
        ]
        for j, v in enumerate(vals, 1):
            ws.cell(row=row, column=j, value=v)
        row += 1

    wb.save(OUT)
    print(f"Saved: {OUT}")


if __name__ == "__main__":
    main()
